# Generated by Django 5.0 on 2024-12-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='hotel_status',
            field=models.BooleanField(default=False),
        ),
    ]
