# Generated by Django 5.0 on 2024-12-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('latitiude', models.TextField()),
                ('longitude', models.TextField()),
                ('hotel_image1', models.ImageField(upload_to='media/hotel_images')),
                ('hotel_image2', models.ImageField(upload_to='media/hotel_images')),
                ('hotel_image3', models.ImageField(upload_to='media/hotel_images')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
