# Generated by Django 5.0 on 2024-12-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='latitiude',
            new_name='latitude',
        ),
    ]
